adb_host_ip: 127.0.0.1
adb_host_port: 5037
device_name: 192.168.137.166:30016
phone_ip: 192.168.137.166
phone_port: 30016
connect_func: ADBORI
app_package: com.orbbec.AstraUnity536Sample
screen_width: 1280
screen_height: 720
test_time: 60
